package com.tobeto.activityTracking.mernis;

//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.0.0.0
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 012D8852B85BE0A1819250CCEA1F62EBB1579F1DB6923FAA30AC0C6F2881DAF18CB54834D58E9E5E226FD56918F7D00206879B9A9FA0FAF346FE859F8413AE64
//------------------------------------------------------------------------
import java.util.Date;


public interface FVNDateTimeConverter
{
    java.util.Date convertDateTime(String strDate);
    java.util.Date convertTime(String strDate);
    java.util.Date convertDate(String strDate);
    String convertDuration(String value);
    String getStringFromDateTime(Date value);
    String getStringFromDate(Date value);
    String getStringFromTime(Date value);
    String getStringFromDuration(String value);
}